FROM node:22-bullseye

WORKDIR /webRtc

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    make \
    g++ \
    build-essential \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json* ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build

EXPOSE 8080
EXPOSE 40000-40999/udp
EXPOSE 41000-41999/udp
EXPOSE 40000-40999/tcp

CMD ["npm", "start"]
